---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-operator.fullname" . }}
  labels:
    {{- include "redis-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
      name: https
  selector:
    {{- include "redis-operator.selectorLabels" . | nindent 4 }}
