name: Update versions in chart/Chart.yaml

on:
  workflow_dispatch:
    inputs:
      version-bump:
        description: 'Whether to bump major, minor or patch version'
        # For exmaple:
        # Bump major version (i.e. current_version=v1.2.3 --> new_version=v2.0.0)'
        # Bump minor version (i.e. current_version=v1.2.3 --> new_version=v1.3.0)
        # Bump patch version (i.e. current_version=v1.2.3 --> new_version=v1.2.4)
        required: false
        default: patch
        type: choice
        options:
        - major
        - minor
        - patch

env:
  REGISTRY: ghcr.io

defaults:
  run:
    shell: bash

jobs:
  update_versions:
    name: Update versions in chart/Chart.yaml
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_USER_GH_TOKEN }}

    - name: Get current version
      id: get_version
      run: echo "chart_version=$(yq eval '.version' chart/Chart.yaml)" >> $GITHUB_OUTPUT

    - name: Get current appVersion
      id: get_appversion
      run: echo "app_version=$(yq eval '.appVersion' chart/Chart.yaml)" >> $GITHUB_OUTPUT

    - name: Bump version
      uses: actions-ecosystem/action-bump-semver@v1
      id: bump_version
      with:
        current_version: ${{ steps.get_version.outputs.chart_version }}
        level: ${{ inputs.version-bump }}

    - name: Bump appVersion
      uses: actions-ecosystem/action-bump-semver@v1
      id: bump_appversion
      with:
        current_version: ${{ steps.get_appversion.outputs.app_version }}
        level: ${{ inputs.version-bump }}

    - name: Update versions in chart/Chart.yaml
      id: update_chart_versions
      run: |
        version=${{ steps.bump_version.outputs.new_version }} appVersion=${{ steps.bump_appversion.outputs.new_version }} yq eval -i '.appVersion = strenv(appVersion) | .version = strenv(version)' chart/Chart.yaml

    - name: Update crds
      run: |
        curl -sSf -L -o $RUNNER_TEMP/regctl https://github.com/regclient/regclient/releases/download/v0.4.8/regctl-linux-amd64
        chmod a+x $RUNNER_TEMP/regctl
        $RUNNER_TEMP/regctl registry login $REGISTRY --user ${{ github.actor }} --pass-stdin <<< ${{ secrets.GITHUB_TOKEN }}
        cd chart/crds
        $RUNNER_TEMP/regctl artifact get -m application/gzip $REGISTRY/sap/redis-operator/crds:${{ steps.bump_appversion.outputs.new_version }} | tar xvz

    - name: Commit changes
      run: |
        git config --global user.name github-actions
        git config --global user.email github-actions@github.com
        git pull
        git add -A
        git commit -m "Bump version(s) in helm chart" || true //do not throw error, when nothing to commit
        git push
